Add CRUD for pending_transactions
status-im/nim-status pull request #119
Opened 2020-12-14 11:31 UTC by siphiuel

2020-12-14 15:43 UTC, jrainville approved these changes
Nice work

2020-12-21 04:35 UTC, emizzle requested changes
Awesome job @siphiuel! The apis have been updated (again - really really sorry) to be in line with the upstream tiny_sqlite APIs. 

We've also landed the ability to automatically get `dbColumnName` and `dbTableName` pragma values for use in queries. I've suggested some edits in the queries to show you what I mean, though I didn't suggest a change for every single query (I think you'll get the idea).

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/pendingtxs.nim
> +  result = execQuery[PendingTx](db, query, networkId, address)
We've updated the tiny_sqlite APIs to be inline with upstream, so this is now:
```nim
result = db.all(PendingTx, query, networkId, address)
```

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/pendingtxs.nim
> +  PendingTx* = object
```suggestion
  PendingTx* {.dbTableName("pending_transactions").} = object
```

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/pendingtxs.nim
> +  result = execQuery[PendingTx](db, query, networkId)
```suggestion
  var pendingTx: PendingTx
  let query = fmt"""SELECT {pendingTx.transactionHash.columnName}, {pendingTx.blkNumber.columnName}, {pendingTx.fromAddress.columnName}, {pendingTx.toAddress.columnName}, {pendingTx.txType.columnName}, {pendingTx.data.columnName} FROM {pendingTx.tableName} WHERE {pendingTx.networkId.columnName} = ?"""

  result = db.all(PendingTx, query, networkId)
```

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/pendingtxs.nim
> +  result = execQuery[PendingTx](db, query, networkId, address)
```suggestion
  var pendingTx: PendingTx
  let query = fmt"""
    SELECT {pendingTx.transactionHash.columnName}, {pendingTx.blkNumber.columnName}, {pendingTx.fromAddress.columnName}, {pendingTx.toAddress.columnName}, {pendingTx.type.columnName}, {pendingTx.data.columnName} 
    FROM {pendingTx.tableName} WHERE {pendingTx.networkId.columnName} = ? AND from_address = ?
  """

  result = db.all(PendingTx, query, networkId, address)
```

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/pendingtxs.nim
> +  let query = fmt"""DELETE FROM pending_transactions WHERE transaction_hash = ?"""
```suggestion
  var pendingTx: PendingTx
  let query = fmt"""DELETE FROM {pendingTx.tableName} WHERE {pendingTx.transactionHash} = ?"""
```

2020-12-21 04:35 UTC, emizzle commented on test/nim/pendingtxs.nim
> +       txs[0].data == "data_json"
Could we compare `txs[0] == tx` instead of explicitly comparing each field?

2020-12-21 04:35 UTC, emizzle commented on nim_status/lib/database.nim
> +  """
```suggestion
  var pendingTx: PendingTx
  let pendingTxsSQL = """
    CREATE TABLE IF NOT EXISTS {pendingTx.tableName} (
        {pendingTx.networkId.columnName} UNSIGNED BIGINT NOT NULL,
        {pendingTx.transactionHash.columnName} VARCHAR NOT NULL,
        {pendingTx.blkNumber.columnName} BIGINT NOT NULL,
        {pendingTx.fromAddress.columnName} VARCHAR NOT NULL,
        {pendingTx.toAddress.columnName} VARCHAR NOT NULL,
        {pendingTx.txType.columnName} VARCHAR NOT NULL,
        {pendingTx.data.columnName} TEXT,
        PRIMARY KEY ({pendingTx.networkId.columnName}, {pendingTx.transactionHash.columnName})
      ) WITHOUT ROWID;
  """
```

2020-12-21 07:11 UTC, siphiuel commented
@emizzle thanks for suggestions and review! Will update

2021-01-08 01:41 UTC, merged