Increase identicon size
status-im/nim-status pull request #162
Opened 2021-03-03 15:30 UTC by richard-ramos

2021-03-03 16:03 UTC, jrainville approved these changes

2021-03-04 14:25 UTC, michaelsbradleyjr requested changes
This PR branch appears to be out-of-date with respect to `master`, e.g. `identicon.nim` is in the wrong location relative to `master`.

@richard-ramos did status-go also change to generate a larger identicon?
a
If not, then these changes will break the Nim and C shim tests for identicon. That's not necessarily a problem, but we ought to then disable those tests so the CI checks pass. Also, I'm not sure of the reason but the GitHub Actions workflow didn't run for this PR.

2021-03-18 15:38 UTC, michaelsbradleyjr commented
Since nim-status is making a break from status-go, my *changes requested* comments above probably aren't relevant.

Should we keep this PR (needs rebase against `master`) or close for now and maybe do it later?

cc: @iurimatias

2021-06-25 02:42 UTC, emizzle commented
Closing due to inactivity.

2021-06-25 02:42 UTC, closed without merging